sources:
  - name: raw
    schema: dbt_rsantos
    tables:
      - name: person_address
      - name: person_stateprovince
      - name: person_countryregion
      - name: person_person
      - name: sales_customer

